ftse_all_share = {
    "3IN": "3i Infrastructure",
    "AAF": "Airtel Africa",
    "AAIF": "Abrdn Asn Inc",
    "AAL": "Anglo American",
    "AAS": "Abrdn Asiafocus",
    "ABDN": "Abrdn",
    "ABF": "AB Foods",
    "ADIG": "Abrdn Di&g",
    "ADM": "Admiral",
    "AEI": "Abrdn Equityinc",
    "AEP": "Anglo-Eastern Plantations",
    "AEWU": "Aew Uk Reit",
    "AGR": "Assura",
    "AGT": "AVI Global Trust",
    "AGVI": "Aberf Geared",
    "AHT": "Ashtead Group",
    "AIE": "Ashoka India Equity Investment Trust Plc",
    "AJB": "AJ Bell",
    "AJOT": "Avi Japan Oppo.",
    "ALFA": "Alfa Fin",
    "ALPH": "Alpha Group International",
    "ALW": "Alliance Witan",
    "AML": "Aston Martin Lagonda",
    "ANII": "Ab New India",
    "ANTO": "Antofagasta",
    "AO.": "Ao World",
    "APAX": "Apax Global Alpha",
    "API": "Abrdn Property",
    "APN": "Applied Nutri",
    "APTD": "Aptitude",
    "ARR": "Aurora Uk Alpha",
    "ASC": "ASOS",
    "ASHM": "Ashmore",
    "ASL": "Aberforth Smaller Companies Trust Plc",
    "ASLI": "Abrdn Euro Log",
    "ATG": "Auction Technology Group",
    "ATR": "Schroder Asian",
    "ATT": "Allianz Technology Trust",
    "AUGM": "Augmentum Fint.",
    "AUSC": "Abrdn Uk Small",
    "AUTO": "Auto Trader",
    "AV.": "Aviva",
    "AVON": "Avon Protection",
    "AZN": "Astrazeneca",
    "BA.": "BAE Systems",
    "BAB": "Babcock",
    "BAG": "Barr (A.G.)",
    "BAKK": "Bakkavor",
    "BARC": "Barclays",
    "BASC": "Brown Advisory",
    "BATS": "British American Tobacco",
    "BBGI": "BBGI Global Infrastructure",
    "BBH": "Bellevue Health",
    "BBOX": "Tritax Big Box",
    "BBY": "Balfour Beatty",
    "BCG": "Baltic Classifieds Group",
    "BERI": "Blackrock Engy",
    "BEZ": "Beazley",
    "BGCG": "Baillie Gif. Ch",
    "BGEO": "Bank Of Georgia Group",
    "BGEU": "Baillie Geu",
    "BGFD": "Baillie Gifford Japan Trust PLC",
    "BGS": "Baillie Gifford Shin Nippon PLC",
    "BGUK": "Baillie Gifford",
    "BHMG": "BH Macro GBP",
    "BIOG": "Biotech Gwth",
    "BIPS": "Invesco Bd In",
    "BKG": "Berkeley Group",
    "BLND": "British Land",
    "BME": "B&M",
    "BMY": "Bloomsbury",
    "BNKR": "Bankers Investment Trust",
    "BNZL": "Bunzl",
    "BOOT": "Henry Boot",
    "BOWL": "Hollywood Bwl",
    "BOY": "Bodycote",
    "BP.": "BP",
    "BPT": "Bridgepoint",
    "BRAI": "Blackrock Ait",
    "BRBY": "Burberry",
    "BREE": "Breedon",
    "BRFI": "Blackrock Fr",
    "BRGE": "BlackRock Greater Europe Investment Trust",
    "BRLA": "Blackrock Lat A",
    "BRSC": "BlackRock Smaller Companies Trust PLC",
    "BRWM": "BlackRock World Mining Trust plc",
    "BSIF": "Bluefield Solar",
    "BT.A": "BT",
    "BTRW": "Barratt Redrow",
    "BUT": "Brunner Inv.tst",
    "BWY": "Bellway",
    "BYG": "Big Yellow",
    "BYIT": "Bytes Tech",
    "CABP": "Cab Payments",
    "CAPD": "Capital",
    "CARD": "Card Factory",
    "CARR": "Carrs Group",
    "CBG": "Close Bros",
    "CCC": "Computacenter",
    "CCH": "Coca-Cola HBC",
    "CCJI": "CC Japan Income",
    "CCL": "Carnival",
    "CCR": "C&C Group",
    "CGT": "Capital Gearing Trust",
    "CHG": "Chemring",
    "CHI": "Ct Uk High",
    "CHRY": "Chrysalis Inves",
    "CKN": "Clarkson",
    "CLDN": "Caledonia",
    "CLI": "CLS Holdings",
    "CLIG": "City Lon Inv",
    "CMCX": "CMC Markets",
    "CNA": "Centrica",
    "CNE": "Capricorn Energy PLC",
    "COA": "Coats",
    "COST": "Costain",
    "CPG": "Compass Group",
    "CPI": "Capita",
    "CRDA": "Croda International",
    "CREI": "Cust Prop Inc",
    "CRST": "Crest Nicholson",
    "CRT": "Care Reit",
    "CSN": "Chesnara",
    "CTEC": "ConvaTec",
    "CTPE": "Ct Priv. Ord",
    "CTUK": "Ct Uk Cap & Inc",
    "CTY": "City Of London Investment",
    "CURY": "Currys",
    "CVCG": "Cvc Ig Gbp",
    "CWK": "Cranswick",
    "CWR": "Ceres Power",
    "CYN": "CQS Natural Resources Growth & Income",
    "DCC": "DCC",
    "DEC": "Diversified Energy",
    "DFS": "Dfs Furn",
    "DGE": "Diageo",
    "DGI9": "Digital 9",
    "DIG": "Dunedin Inc.",
    "DIVI": "Diverse Inc",
    "DLAR": "De La Rue",
    "DLG": "Direct Line",
    "DLN": "Derwent London",
    "DNLM": "Dunelm",
    "DOCS": "Dr. Martens",
    "DOM": "Dominos",
    "DORE": "Downing Renewa.",
    "DPLM": "Diploma",
    "DRX": "Drax",
    "DSCV": "DiscoverIE",
    "DWL": "Dowlais",
    "EAT": "European Assets Trust",
    "ECEL": "Eurocell",
    "ECOR": "Ecora Res.",
    "EDIN": "Edinburgh Investment Trust PLC",
    "EDV": "Endeavour Mining",
    "EGL": "Ecofin Global",
    "ELM": "Elementis",
    "EMG": "Man",
    "ENOG": "Energean Oil & Gas",
    "ENQ": "Enquest",
    "ENRG": "Vh Global Ener.",
    "ENT": "Entain",
    "EOT": "Euro Opps Tr.",
    "ESCT": "The European Smaller Companies Trust",
    "ESNT": "Essentra",
    "ESP": "Empiric",
    "EVOK": "Evoke",
    "EWI": "Edinburgh Worldwide Investment Trust",
    "EXPN": "Experian",
    "EZJ": "easyJet",
    "FAN": "Volution Group PLS",
    "FAS": "Fidelity Asian Values",
    "FCH": "Funding Circle",
    "FCIT": "F&C Investment Trust",
    "FCSS": "Fidelity China Special Situations PLC",
    "FDM": "FDM Group",
    "FEML": "Fidelity E.m.ld",
    "FEV": "Fidelity European Values",
    "FGEN": "Foresight Envr",
    "FGP": "Firstgroup",
    "FGT": "Finsbury Growth",
    "FJV": "Fidelity Japan Trust",
    "FORT": "Forterra",
    "FOUR": "4Imprint",
    "FOXT": "Foxtons",
    "FRAS": "Frasers Group",
    "FRES": "Fresnillo",
    "FSFL": "Foresight Solar Fund",
    "FSG": "Foresight Group Holdings",
    "FSJ": "James Fisher and Sons",
    "FSTA": "Fuller Smith & Turner",
    "FSV": "Fidelity",
    "FUTR": "Future",
    "FXPO": "Ferrexpo",
    "GABI": "Gcp Asset Bckd",
    "GAW": "Games Workshop",
    "GCP": "GCP Infrastructure Investments",
    "GDWN": "Goodwin",
    "GEN": "Genuit Group",
    "GFRD": "Galliford Try",
    "GFTU": "Grafton Group",
    "GLE": "MJGleeson",
    "GLEN": "Glencore",
    "GMS": "Gulf Marine Services",
    "GNC": "Greencore",
    "GNS": "Genus",
    "GOT": "Gotech Group",
    "GPE": "GPE",
    "GRG": "Greggs",
    "GRI": "Grainger plc",
    "GROW": "Molten Ventures",
    "GSCT": "Glb Sml Co Trst",
    "GSF": "Gore Street En.",
    "GSK": "Glaxosmithkline",
    "GYM": "Gym Grp",
    "HAS": "Hays",
    "HBR": "Harbour Energy",
    "HEAD": "Headlam",
    "HET": "Hend.eur.trust",
    "HFD": "Halfords",
    "HFEL": "Hend.far East",
    "HFG": "Hilton Foods",
    "HGT": "HgCapital Trust plc",
    "HHI": "Henderson High Income Trust",
    "HICL": "HICL Infrastructure",
    "HIK": "Hikma Pharmaceuticals",
    "HILS": "Hill & Smith",
    "HINT": "Henderson Int.",
    "HLCL": "Helical Bar",
    "HLMA": "Halma",
    "HLN": "Haleon",
    "HMSO": "Hammerson",
    "HOC": "Hochschild",
    "HRI": "Herald Investment Trust",
    "HSBA": "HSBC Holdings",
    "HSL": "Henderson Smaller Companies Trust",
    "HSW": "Hostelworld",
    "HSX": "Hiscox",
    "HTG": "Hunting",
    "HTWS": "Helios Towers",
    "HVPE": "HarbourVest Private Equity",
    "HWDN": "Howden Joinery",
    "HWG": "Harworth Gp",
    "IAD": "Invesco Asia",
    "IAG": "International Airlines",
    "IBST": "Ibstock",
    "IBT": "Int.biotech.",
    "ICG": "Int.cap.grp",
    "ICGT": "ICG Enterprise Trust",
    "IDS": "International Distributions Services",
    "IEM": "Impax Asset Management",
    "IGC": "India Cap",
    "IGET": "Invesco Gl Eq",
    "IGG": "IG",
    "IHG": "InterContinental Hotels",
    "IHP": "IntegraFin Holdings",
    "III": "3i Group",
    "IMB": "Imperial Brands",
    "IMI": "IMI",
    "INCH": "Inchcape",
    "INF": "Informa",
    "INOV": "Schroders Cap",
    "INPP": "International Public Partnerships",
    "INVP": "Investec",
    "IPF": "Inter. Pers.",
    "IPO": "Ip Group",
    "ITH": "Ithaca Energy",
    "ITRK": "Intertek Group",
    "ITV": "ITV",
    "IWG": "IWG",
    "JAGI": "Jp Morg.as",
    "JAM": "JPMorgan American",
    "JARA": "Jpmorgan Global",
    "JCGI": "Jp Morg.chin",
    "JCH": "Jpmorgan Clav",
    "JD.": "JD Sports",
    "JDW": "Wetherspoon (J.D)",
    "JEDT": "JPMorgan European Discovery Trust",
    "JEGI": "Jpmorgan Euro.",
    "JEMI": "Jpmorgan Glob",
    "JFJ": "JPMorgan Japanese",
    "JGGI": "JPMorgan Global Growth & Income",
    "JII": "JPMorgan Indian",
    "JMAT": "Johnson Matthey",
    "JMG": "JPMorgan Emerging Markets Investment Trust",
    "JTC": "Jtc Plc",
    "JUGI": "Jpm Uk Sml Cap",
    "JUP": "Jupiter Fund Management",
    "JUSC": "Jpmorg.us",
    "JUST": "Just Group",
    "KGF": "Kingfisher",
    "KIE": "Kier",
    "KLR": "Keller",
    "KMR": "Kenmare Resources",
    "KNOS": "Kainos Group",
    "LABS": "Life Science",
    "LAND": "Land Securities",
    "LGEN": "Legal & General",
    "LIO": "Liontrust Asset Management",
    "LLOY": "Lloyds",
    "LMP": "LondonMetric",
    "LRE": "Lancashire Holdings",
    "LSEG": "London Stock Exchange",
    "LSL": "Lsl Prop",
    "LTI": "Lindsell Train",
    "LUCE": "Luceco",
    "LWDB": "Law Debenture",
    "LWI": "Lowland Inv.",
    "MAB": "Mitchells & Butlers",
    "MACF": "Macfarlane Grp.",
    "MAJE": "Majedie Inv.",
    "MARS": "Marstons",
    "MCB": "Mcbride",
    "MCG": "Mobico Group",
    "MCT": "Middlefield Prf",
    "MEGP": "ME Group",
    "MER": "Mears",
    "MGAM": "Morgan Advanced Materials",
    "MGCI": "M&g Credit Inc.",
    "MGNS": "Morgan Sindall Group",
    "MKS": "Marks & Spencer",
    "MMIT": "Mobius Investm.",
    "MNDI": "Mondi",
    "MNG": "M&G",
    "MNKS": "Monks Inv",
    "MNL": "Manchester&lon.",
    "MONY": "Moneysupermarket.Com",
    "MOON": "Moonpig Gr",
    "MOTR": "Motorpoint",
    "MRC": "Mercantile Investment Trust PLC",
    "MRCH": "Merchants Trust",
    "MRO": "Melrose",
    "MSLH": "Marshalls",
    "MTE": "Montanaro",
    "MTO": "Mitie",
    "MTRO": "Metro Bank",
    "MTU": "Montanaro Uk",
    "MUT": "Murray Income Trust",
    "MWY": "Mid Wynd International Investment Trust",
    "MYI": "Murray International",
    "N91": "Ninety One",
    "NAIT": "North American",
    "NAS": "North Atl.smlr",
    "NAVF": "Nippon Active .",
    "NBPE": "Nb Priv. Eqty",
    "NCC": "Ncc",
    "NCYF": "Cqs New C.h.y.f",
    "NESF": "NextEnergy Solar",
    "NG.": "National Grid",
    "NRR": "NewRiver",
    "NWG": "Natwest",
    "NXR": "Norcros",
    "NXT": "Next",
    "OCDO": "Ocado",
    "OCN": "Ocean Wilsons",
    "OIG": "Oryx International Growth",
    "OIT": "Odyssean Inves.",
    "ONT": "Oxford Nano",
    "ORIT": "Octopus Energy",
    "OSB": "OneSavings Bank",
    "OTB": "On The Beach",
    "OXB": "Oxford Biomedica",
    "OXIG": "Oxford Instruments",
    "PAC": "Pacific Assets",
    "PAG": "Paragon Group",
    "PAGE": "PageGroup",
    "PAY": "Paypoint",
    "PBEE": "Pensionbee",
    "PCA": "Palace Capital",
    "PCFT": "Polar Cap Gbl",
    "PCGH": "Polar Cap Glbl",
    "PCT": "Polar Capital Technology Trust",
    "PCTN": "Picton Prop",
    "PDL": "Petra Diamonds",
    "PETS": "Pets at home",
    "PFC": "Petrofac",
    "PFD": "Premier Foods",
    "PHAR": "Pharos Energy",
    "PHI": "Pacific Horizon",
    "PHLL": "Petershill",
    "PHNX": "Phoenix Group Holdings",
    "PHP": "Primary Health",
    "PIN": "Pantheon International",
    "PINE": "Pinewood Tech",
    "PINT": "Pantheon Infr",
    "PLUS": "Plus500",
    "PNL": "Personal Assets Trust",
    "PNN": "Pennon",
    "POLN": "Pollen Street",
    "PPET": "Patria Private",
    "PPH": "Pphe Hotel",
    "PRSR": "Prs Reit",
    "PRTC": "PureTech",
    "PRU": "Prudential",
    "PRV": "Porvair",
    "PSDL": "Phoenix Spree D",
    "PSH": "Pershing Square Holdings",
    "PSN": "Persimmon",
    "PSON": "Pearson",
    "PTEC": "Playtech",
    "PZC": "Pz Cussons",
    "QLT": "Quilter",
    "QQ.": "Qinetiq",
    "RAT": "Rathbone",
    "RCDO": "Ricardo",
    "RCH": "Reach Plc",
    "RCP": "RIT Capital Partners",
    "REC": "Record",
    "RECI": "Real Est.cred",
    "REL": "Relx",
    "RESI": "Residential Sec",
    "RGL": "Regional Reit",
    "RHIM": "RHI Magnesita",
    "RICA": "Ruffer",
    "RIII": "Rights &iss.",
    "RIO": "Rio Tinto",
    "RKT": "Reckitt",
    "RMII": "Rm Infra Inc",
    "RMV": "Rightmove",
    "RNK": "Rank",
    "ROO": "Deliveroo",
    "ROR": "Rotork",
    "RPI": "Raspberry Pi",
    "RR.": "Rolls-Royce",
    "RS1": "RS Group",
    "RSE": "Riverstone Energy",
    "RSW": "Renishaw",
    "RTO": "Rentokil Initial",
    "RWA": "Robert Walters",
    "RWI": "Renewi Plc",
    "SAFE": "Safestore",
    "SAGA": "Saga",
    "SAIN": "Scot.amer.inv.",
    "SBRE": "Sabre Insur",
    "SBRY": "Sainsbury's",
    "SCF": "Schroder Income Growth Fund",
    "SCP": "Schroder UK Mid & Small Cap Fund",
    "SCT": "Softcat",
    "SDP": "Schroder AsiaPacific Fund",
    "SDR": "Schroders",
    "SDY": "Speedy Hire",
    "SEC": "Strategic Eqty",
    "SEIT": "Sdcl Energy Ef.",
    "SEQI": "Sequoia Economic Infrastructure Fund",
    "SERE": "Schroder Eur.r",
    "SFR": "Severfield",
    "SGE": "Sage Group",
    "SGRO": "Segro",
    "SHC": "Shaftesbury Capital",
    "SHED": "Urban Logistics",
    "SHEL": "Shell",
    "SHI": "SIG",
    "SHRS": "Shires Inc.",
    "SJG": "Schroder Japan",
    "SMIF": "Twentyfour Sel",
    "SMIN": "Smiths Group",
    "SMT": "Scottish Mortgage",
    "SMWH": "Wh Smith",
    "SN.": "Smith & Nephew",
    "SNR": "Senior",
    "SNWS": "Smiths News",
    "SOHO": "Social Housing",
    "SOI": "Schroders",
    "SPI": "Spire Healthcare",
    "SPT": "Spirent",
    "SPX": "Spirax-Sarco",
    "SRE": "Sirius Real Estate",
    "SREI": "Schroder Real",
    "SRP": "Serco",
    "SSE": "SSE",
    "SSIT": "Seraphim Sp",
    "SSON": "Smithson Invest",
    "SSPG": "SSP Group",
    "SST": "Scot.orntl.smll",
    "STAN": "Standard Chartered",
    "STB": "Secure Trust",
    "STEM": "SThree",
    "STJ": "St James's Place",
    "STS": "Sts Global Inc",
    "STVG": "Stvg",
    "SUPR": "Supermarket Income",
    "SUS": "S & U",
    "SVS": "Savills",
    "SVT": "Severn Trent",
    "SWEF": "Starwood Eur",
    "SXS": "Spectris",
    "SYNC": "Syncona",
    "SYNT": "Synthomer",
    "TATE": "Tate & Lyle",
    "TBCG": "TBC Bank Group",
    "TCAP": "TP ICAP",
    "TEM": "Templeton Emerging Markets",
    "TEP": "Telecom Plus",
    "TET": "Treatt",
    "TFIF": "Twentyfour Inc",
    "THRG": "Throgmorton Trust",
    "THRL": "Target Healthc.",
    "TLW": "Tullow Oil",
    "TMIP": "Taylor Maritim",
    "TMPL": "Temple Bar Investment Trust",
    "TPK": "Travis Perkins",
    "TPT": "Topps Tiles",
    "TRI": "Trifast",
    "TRIG": "Renewables Infrastructure Group",
    "TRN": "Trainline",
    "TRST": "Trustpilot",
    "TRY": "TR Property Investment Trust",
    "TSCO": "Tesco",
    "TTG": "Tt Electronics",
    "TW.": "Taylor Wimpey",
    "UEM": "Utilico Emerging Markets",
    "UKW": "Greencoat UK Wind",
    "ULTP": "Ultimate Products",
    "ULVR": "Unilever",
    "USA": "Baillie Gifford US Growth Trust",
    "UTG": "Unite",
    "UU.": "United Utilities",
    "VANQ": "Vanquis Banking",
    "VCT": "Victrex",
    "VEIL": "Vietnam Enterprise Investments",
    "VID": "Videndum Plc",
    "VIP": "Vipera",
    "VNH": "Vietnam Holdings",
    "VOD": "Vodafone",
    "VOF": "VinaCapital Vietnam Opportunity Fund",
    "VP.": "Vp",
    "VSL": "Vpc Specialty",
    "VSVS": "Vesuvius",
    "VTY": "Vistry Grp",
    "WEIR": "Weir Group",
    "WG.": "Wood Group (J)",
    "WHR": "Warehouse Reit",
    "WIX": "Wickes Group P.",
    "WIZZ": "Wizz Air",
    "WKP": "Workspace",
    "WOSG": "Watches Switz",
    "WPP": "WPP",
    "WPS": "Wag Payment",
    "WTB": "Whitbread",
    "WWH": "Worldwide Healthcare Trust",
    "XAR": "Xaar",
    "XPP": "Xp Power",
    "XPS": "Xps Pensions",
    "ZIG": "Zigup",
    "ZTF": "Zotefoams",
}
