# This workflow will build the project and run formatting/lint checks
name: Maven Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run Python tests with coverage
        working-directory: timeseries-python
        run: |
          pip install -r requirements.txt
  
          # Run tests with coverage
          pip install coverage pytest pytest-cov
          coverage run -m pytest
          coverage xml

          # Fail the build if overall coverage drops below 80%
          coverage report --fail-under=80
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: ui/package-lock.json
      - name: Build UI
        working-directory: ui
        run: |
          npm ci
          npm run build
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Log in to container registry
        # Registry credentials are provided via encrypted GitHub secrets
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./timeseries-lambda
          file: ./timeseries-lambda/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/pension-risk-management-system/timeseries-lambda:latest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
